config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :home, only: :index
  root 'home#index'
  get 'parking', to: 'home#parking'
  get 'help', to:'home#help'
  post 'help', to: 'home#create_helper'
  get 'price', to:'home#price'
  get 'home/floors', to:'home#get_floors'

  namespace :client do
    resources :booking do
      collection do
        get 'get_floors'
        get 'get_slot_detail'
        put 'cancel_slot'
      end
    end
    resources :profile do
      member do
        get 'create_profile'
        delete 'destroy_vehicle'
        get 'history'
      end
      collection do
        patch 'update_password'
        patch 'upload_avatar'
        post 'create_vehicle'
      end
    end
  end

  namespace :admin do
    resources :booking
    resources :managers do
      collection do
        get 'edit_profile'
        patch 'update_profile'
        get 'edit_password'
        patch 'update_password'
        get 'update_parking'
        get 'remove_parking'
        get 'get_manager'
        get 'clients'
        get 'get_profile'
        get 'helps'
        get 'help_isread'
        put 'manager_reset_password'
      end
    end
    resources :parking do
      collection do
        get 'get_floors'
      end
    end
  end

  namespace :manager do
    resources :booking, only: [:index] do
      collection do
        get 'load_park'
        get 'get_slot_detail'
        post 'slot_book'
        put 'pay'
        get 'get_reserve_detail'
        put 'cancel_reserve'
        post 'accept_reserve'
        get 'find_bks'
      end
    end
    resources :profile, only: [:edit, :update] do
      member do
        get 'payment_history'
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/admin/managers_controller.rb
class Admin::ManagersController < Admin::BaseController
  before_action :set_profile, only: %i(edit_profile update_profile)

  def index
    @managers = User.includes(:profile).where(role: '1')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    password = (0...8).map { ('a'..'z').to_a[rand(26)] }.join
    @user.password = password
    @user.confirmed_at = DateTime.now
    @user.skip_confirmation!
    @user.role = '1'

    @profile = @user.build_profile profile_params
    if @user.save && @profile.save
      SendMailJob.set(wait: 3.seconds).perform_later(@user.email, password)
      flash[:success] = 'Thành công.'
      redirect_to new_admin_manager_path
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_admin_manager_path
    end
  end

  def edit_profile
  end

  def update_profile
    if @profile.update_attributes profile_params
      flash[:success] = 'Đã cập nhật!'
      redirect_to edit_profile_admin_managers_path
    else
      flash[:errors] = @profile.errors.full_messages
      redirect_to edit_profile_admin_managers_path
    end
  end

  def update_parking
    @manager = User.find_by(id: params[:user_id], role: '1')
    respond_to do |format|
      if params[:parking_id].nil? || params[:user_id].nil? || @manager.nil?
        format.json { render json: false, status: 404 }
      else
        if @manager.update_attribute(:parking_id, params[:parking_id])
          format.json { render json: @manager, status: :ok }
        else
          format.json { render json: @manager.errors, status: 500 }
        end
      end
    end
  end

  def remove_parking
    @manager = User.find_by(id: params[:user_id], role: '1')
    respond_to do |format|
      if params[:user_id].nil? || @manager.nil?
        format.json { render json: false, status: 404 }
      else
        if @manager.update_attribute(:parking_id, nil)
          format.json { render json: @manager, status: :ok }
        else
          format.json { render json: @manager.errors, status: 500 }
        end
      end
    end
  end

  def get_manager
    @manager = User.find_by(parking_id: params[:parking_id], role: '1')
    @profile = Profile.find_by(user_id: @manager.id) if @manager.present?
    respond_to do |format|
      if params[:parking_id].nil? || @manager.nil? || @profile.nil?
        format.json { render json: false, status: 404 }
      else
        format.json { render json: @profile.as_json(only: [:first_name, :last_name]), status: :ok }
      end
    end
  end

  def edit_password
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_password_params)
      bypass_sign_in(@user)
      flash[:success] = 'Đã cập nhật'
      redirect_to edit_password_admin_managers_path
    else
      flash[:error] = 'Thất bại !'
      redirect_to edit_password_admin_managers_path
    end
  end

  def clients
    @clients = User.includes(:profile).where(role: '0')
  end

  def get_profile
    @total = ParkingSlotReservation.client_paid(Vehicle.where(user_id: params[:user_id]).pluck(:number_plate))
    @month = ParkingSlotReservation.client_paid_month(Vehicle.where(user_id: params[:user_id]).pluck(:number_plate))
    respond_to do |format|
      unless @total.present?
        format.json { render json: false, status: 404 }
      else
        format.json { render json: { total: @total, month: @month}, status: :ok }
      end
    end
  end

  def helps
    @helps = Helper.all.order(is_read: :asc, created_at: :desc).paginate(page: params[:page], per_page: 5)
  end

  def help_isread
    @help = Helper.find_by id: params[:id]
    if @help.update(is_read: true)
      flash[:success] = 'Đã cập nhật.'
    else
      flash[:error] = 'Thất bại !'
    end
    redirect_to helps_admin_managers_path
  end

  def manager_reset_password
    @manager = User.find_by(id: params[:m_id], role: '1')
    return false unless @manager.present?

    respond_to do |format|
      if @manager.update(user_password_params)
        SendMailJob.set(wait: 3.seconds).perform_later(@manager.email, user_password_params[:password])
        format.json { render json: false, status: :ok }
      else
        format.json { render json: false, status: 404 }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
  def user_password_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :phone, :address, :user_id)
  end
  def set_profile
    @profile = Profile.find_by user_id: @admin.id
    @profile = @admin.build_profile unless @profile.present?
  end
end

app/controllers/manager/base_controller.rb
class Manager::BaseController < ApplicationController
  layout 'manager'

  before_action :authenticate_user!
  before_action :is_manager?

  private

  def is_manager?
    unless current_user.role == '1'
      flash[:error] = 'Access Denied !!!'
      redirect_to root_path
    end
  end
end

app/controllers/manager/booking_controller.rb
class Manager::BookingController < Manager::BaseController
  before_action :set_park, only: %i(index load_park)

  def index
    if @parking.present?
      @parking_address = @parking.address
    else
      @parking_address = 'Bạn chưa quản lý bãi nào hoặc bãi đã đóng cửa.'
    end
  end

  def slot_book
    @slot = ParkingSlot.find_by id: params[:slot_id]
    @parking_slot_reservation = @slot.parking_slot_reservations.build(number_plate: params[:number_plate], timein: DateTime.now, user_id: current_user.id)
    respond_to do |format|
      unless @slot.present? || @slot.status != '2' || params[:number_plate].size < 10
        format.json { render json: false, status: 404 }
      end
      if params[:type] == 'day'
        if @slot.update(status: '2', number_plate: params[:number_plate], date_in: DateTime.now) && @parking_slot_reservation.update(price: @slot.price_by_hours )
          format.json { render json: false, status: :ok }
        else
          format.json { render json: false, status: 404 }
        end
      else
        subtotal = @slot.price_by_months.to_i * params[:quantity].to_i
        timeout = DateTime.now + params[:quantity].to_i.month
        if @slot.update(status: '2', number_plate: params[:number_plate], date_in: DateTime.now) && @parking_slot_reservation.update(is_paid: true, price: @slot.price_by_months, subtotal: subtotal, timeout: timeout, is_monthly: true, park_id: @slot.block.floor.parking_id)
          SlotExpiredJob.set(wait: params[:quantity].to_i.minutes).perform_later(@slot.id, true)
          format.json { render json: false, status: :ok }
        else
          format.json { render json: false, status: 404 }
        end
      end
    end
  end

  def get_slot_detail
    @parking_slot_reservation = ParkingSlotReservation.where(parking_slot_id: params[:slot_id]).order("id DESC").first
    respond_to do |format|
      unless @parking_slot_reservation.present?
        format.json { render json: false, status: 404 }
      else
        format.json { render json: @parking_slot_reservation.as_json(except: %i(created_at updated_at user_id), methods: [:total_time]), status: :ok }
      end
    end
  end

  def load_park
    respond_to do |format|
      if params[:size] && ['1','2','3'].include?(params[:size]) && @parking.present?
        @floors = Floor.get_floors(@parking.id, params[:size])
        format.json { render json: @floors.as_json(except: [:created_at, :updated_at], include: { blocks: { except: %i(created_at updated_at), include: { parking_slots: { except: %i(block_id created_at updated_at) } } }}), status: :ok }
      else
        format.json { render json: false, status: 404 }
      end
    end
  end

  def pay
    @parking_slot_reservation = ParkingSlotReservation.find_by id: params[:reserve_id]
    respond_to do |format|
      unless @parking_slot_reservation.present?
        format.json { render json: false, status: 404 }
      else
        @slot = @parking_slot_reservation.parking_slot
        subtotal = @slot.price_by_hours.to_i * @parking_slot_reservation.total_time
        if @slot.reserve_expired && @parking_slot_reservation.update(is_paid: true, timeout: DateTime.now, subtotal: subtotal, park_id: @slot.block.floor.parking_id)
          format.json { render json: @parking_slot_reservation, status: :ok }
        else
          format.json { render json: false, status: 404 }
        end
      end
    end
  end

  def get_reserve_detail
    @slot = ParkingSlot.find_by id: params[:slot_id]
    respond_to do |format|
      unless @slot.present?
        format.json { render json: false, status: 404 }
      else
        format.json { render json: @slot.as_json(only: [:id, :date_in, :number_plate]), status: :ok }
      end
    end
  end

  def cancel_reserve
    @slot = ParkingSlot.find_by id: params[:slot_id]
    respond_to do |format|
      if @slot.present? && @slot.reserve_expired
        format.json { render json: false, status: :ok }
      else
        format.json { render json: false, status: 404 }
      end
    end
  end

  def accept_reserve
    @slot = ParkingSlot.find_by id: params[:slot_id]
    @parking_slot_reservation = @slot.parking_slot_reservations.build(number_plate: params[:bks], timein: DateTime.now, user_id: current_user.id, price: @slot.price_by_hours)
    respond_to do |format|
      if @parking_slot_reservation.save && @slot.update(status: '2')
        format.json { render json: false, status: :ok }
      else
        format.json { render json: false, status: 404 }
      end
    end
  end

  def find_bks
    @slot = ParkingSlot.find_by number_plate: params[:bks]
    @floor = Floor.joins(blocks: :parking_slots).where(blocks: { parking_slots: { id: @slot.id } }).take()
    case @floor.size
    when '1'
      size = '4 - 7 chỗ'
    when '2'
      size = '12 - 16 chỗ'
    when '3'
      size = 'Trên 16 chỗ'
    end
    slotname = @slot.block.floor.name + '-' + @slot.block.name + ' - ' + @slot.name
    respond_to do |format|
      if @slot.present?
        format.json { render json: { park: @floor.parking.address, size: size, slotname: slotname }, status: :ok }
      else
        format.json { render json: false, status: 404 }
      end
    end
  end

  private

  def set_park
    @parking = Parking.find_by id: current_user.parking_id, active: true
  end
end

app/controllers/manager/profile_controller.rb
class Manager::ProfileController < Manager::BaseController

  before_action :set_user_profile

  def edit
  end

  def update
    if params[:commit] == 'Update'
      if @user.update_with_password(user_params)
        bypass_sign_in(@user)
        flash[:success] = 'Đã cập nhật.'
        redirect_to edit_manager_profile_path(@user)
      else
        flash[:error] = 'Thất bại !'
        redirect_to edit_manager_profile_path(@user)
      end
    elsif params[:commit] == 'Save'
      if @profile.update_attributes profile_params
        flash[:success] = 'Đã lưu.'
        redirect_to edit_manager_profile_path(@user)
      else
        flash[:errors] = @profile.errors.full_messages
        redirect_to edit_manager_profile_path(@user)
      end
    end
  end

  def payment_history
    @payments = ParkingSlotReservation.where(user_id: @user.id, is_paid: true).order('id DESC').paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html {}
      format.xlsx do
        send_data(ParkingSlotReservation.export_file, :disposition => 'attachment', :type => 'application/excel', :filename => "ThongKe.xlsx")
      end
    end
  end

  private

  def set_user_profile
    @profile = Profile.find_by user_id: current_user.id
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :phone, :address)
  end
end

app/helpers/admin/managers_helper.rb
module Admin::ManagersHelper
end

app/helpers/manager/base_helper.rb
module Manager::BaseHelper
end

app/helpers/manager/booking_helper.rb
module Manager::BookingHelper
end

app/helpers/manager/profile_helper.rb
module Manager::ProfileHelper
end

app/views/admin/managers/clients.html.erb
<style media="screen">
  .pagination {
    justify-content: center;
  }
  .modal-header {
    background-color: #00c851;
  }
  .modal-title {
    color: #fff;
  }
</style>

<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <%= render 'layouts/admin/menu' %>

      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
          Danh Sách Khách Hàng
        </div>
        <div class="card-body" style="padding-bottom: 0px;">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Email</th>
                  <th>Họ và tên</th>
                  <th>Số điện thoại</th>
                  <th>Chi tiêu</th>
                </tr>
              </thead>
              <tbody>
                <% @clients.each_with_index do |m,i| %>
                <tr>
                  <td><%= i+1 %></td>
                  <td><%= m.email %></td>
                  <td><%= m.profile.first_name + ' ' + m.profile.last_name if m.profile.present? %></td>
                  <td><%= m.profile.phone if m.profile.present? %></td>
                  <td>
                    <a href="javascript:void(0)" class="btn btn-outline-success btn-md waves-effect btn-user" data-uid="<%= m.id %>">Xem</a>
                  </td>
                </tr>
                <% end %>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <footer class="sticky-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © DANA CAR PARKING 2019</span>
        </div>
      </div>
    </footer>
  </div>

  <div class="modal fade right" id="fullHeightModalRight" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">

  <div class="modal-dialog modal-side modal-top-right" role="document">


    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title w-100" id="myModalLabel" style="font-size: 1.55rem;">Lịch sử gửi xe</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <div class="row">
            <div class="col-md-5"><b>Tháng này:</b></div>
            <div class="col-md-7"></div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-5"><b>Tất cả:</b></div>
            <div class="col-md-7"></div>
          </div>
        </div>
      </div>
      <div class="modal-footer justify-content-center">
        <button type="button" class="btn btn-outline-success btn-md waves-effect" data-dismiss="modal">Đóng</button>
      </div>
    </div>
  </div>
</div>

</div>

app/views/admin/managers/edit_password.html.erb
<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <%= render 'layouts/admin/menu' %>

      <!-- Area Chart Example-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-id-card fa-lg"></i>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-12">
              <h4>Thay đổi mật khẩu</h4>
              <hr>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= form_for @user, url: update_password_admin_managers_path, method: :patch do |f| %>
                <div class="form-group row">
                  <label class="col-4 col-form-label">Mật khẩu mới: </label>
                  <div class="col-8">
                    <%= f.password_field :password, :autocomplete => "off", class: 'form-control'  %>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="col-4 col-form-label">Xác nhận mật khẩu mới: </label>
                  <div class="col-8">
                    <%= f.password_field :password_confirmation, class: 'form-control' %>
                  </div>
                </div>
                <div class="form-group row">
                  <label class="col-4 col-form-label">Mật khẩu hiện tại: </label>
                  <div class="col-8">
                    <%= f.password_field :current_password, :autocomplete => "off", class: 'form-control'  %>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="offset-4 col-8">
                    <%= f.submit 'Cập nhật', class: 'btn btn-primary' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>


    </div>
    <!-- /.container-fluid -->

    <!-- Sticky Footer -->
    <footer class="sticky-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © Your Website 2019</span>
        </div>
      </div>
    </footer>

  </div>
  <!-- /.content-wrapper -->

</div>

app/views/admin/managers/edit_profile.html.erb
<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <%= render 'layouts/admin/menu' %>

      <!-- Area Chart Example-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-id-card fa-lg"></i> |
          Thông tin tài khoản
        </div>
        <div class="card-body">
          <div class="col-8">
            <%= form_for @profile, url: update_profile_admin_managers_path, method: :patch, html: { class: 'admin_profile' } do |f| %>
            <%= f.hidden_field :user_id %>
            <div class="form-group">
              <%= f.label :first_name, 'Họ' %>
              <%= f.text_field :first_name, class: 'form-control', readonly: true %>
            </div>
            <div class="form-group">
              <%= f.label :last_name, 'Tên' %>
              <%= f.text_field :last_name, class: 'form-control', readonly: true %>
            </div>
            <div class="form-group">
              <%= f.label :phone, 'Số điện thoại' %>
              <%= f.text_field :phone, class: 'form-control phone', readonly: true %>
            </div>
            <div class="form-group">
              <%= f.label :address, 'Địa chỉ' %>
              <%= f.text_field :address, class: 'form-control', readonly: true %>
            </div>
            <div id="div-update" class="form-group" style="display: none;">
              <%= f.submit "Cập nhật", class: 'btn btn-primary' %>
              <button class="btn btn-secondary btn-cancel" style="margin-left: 15px;">Hủy</button>
            </div>
            <div id="div-change" class="form-group">
              <button class="btn btn-info btn-change">Thay đổi</button>
            </div>
            <% end %>
          </div>
        </div>
      </div>


    </div>

    <footer class="sticky-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © Your Website 2019</span>
        </div>
      </div>
    </footer>

  </div>

</div>

app/views/admin/managers/helps.html.erb
<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <%= render 'layouts/admin/menu' %>

      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
          Danh Sách Phản Hồi Của Khách Hàng
        </div>
        <div class="card-body" style="padding-bottom: 0px;">
          <div class="table-responsive">
            <table class="table" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Email</th>
                  <th>Họ và tên</th>
                  <th>Số điện thoại</th>
                  <th>Nội dung</th>
                  <th>Trạng thái</th>
                </tr>
              </thead>
              <tbody>
                <% @helps.each_with_index do |h,i| %>
                <tr>
                  <% if params[:page].present? && params[:page].to_i > 1 %>
                  <td><%= (i+1) + ((params[:page].to_i - 1) * 5) %></td>
                  <% else %>
                  <td><%= i+1 %></td>
                  <% end %>
                  <td><%= h.email %></td>
                  <td><%= h.name %></td>
                  <td><%= h.phone %></td>
                  <td><%= h.content %></td>
                  <% unless h.is_read %>
                  <td style="padding-top: 10px;">
                    <%= link_to '<i class="fas fa-envelope fa-lg"></i>'.html_safe, help_isread_admin_managers_path(id: h.id), class: 'btn btn-light-blue', style: 'color: #fff;', data: { confirm: 'Bạn có chắc chắn ?' } %>
                  </td>
                  <% else %>
                  <td><i class="far fa-check-circle fa-2x" style="color: #00c851!important"></i></td>
                  <% end %>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-9 mx-auto" style="display: flex; justify-content: center;">
              <%= will_paginate @helps, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <footer class="sticky-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © DANA CAR PARKING 2019</span>
        </div>
      </div>
    </footer>
  </div>

</div>

app/views/admin/managers/new.html.erb
<style media="screen">
  label.error {
    color: red;
    font-weight: 500;
    padding-left: 5px;
    font-size: 14px;
    margin-bottom: 0;
  }
</style>

<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-users"></i> |
          Tạo mới nhân viên
        </div>
        <div class="card-body">
          <div class="col-8">
            <%= form_for @user, url: admin_managers_path do |f| %>
              <div class="form-group">
                <%= f.label :email ,"Email"%>
                <%= f.email_field :email, class: 'form-control', required: true %>
              </div>
              <%= fields_for :profile do |ff| %>
                <div class="form-group">
                  <%= ff.label :first_name,"Họ và tên lót" %>
                  <%= ff.text_field :first_name, class: 'form-control', required: true %>
                </div>
                <div class="form-group">
                  <%= ff.label :last_name,"Tên" %>
                  <%= ff.text_field :last_name, class: 'form-control', required: true %>
                </div>
                <div class="form-group">
                  <%= ff.label :phone,"Số điện thoại" %>
                  <%= ff.text_field :phone, class: 'form-control phone', required: true %>
                </div>
                <div class="form-group">
                  <%= ff.label :address,"Địa chỉ" %>
                  <%= ff.text_field :address, class: 'form-control', required: true %>
                </div>
              <% end %>
              <div class="form-group">
                <%= f.submit 'Tạo mới', class: 'btn btn-primary' %>
              </div>
            <% end %>
          </div>

        </div>
      </div>

    </div>
    <!-- /.container-fluid -->

    <!-- Sticky Footer -->
    <footer class="sticky-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © DANA CAR PARKING</span>
        </div>
      </div>
    </footer>

  </div>
  <!-- /.content-wrapper -->

</div>