config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :home, only: :index
  root 'home#index'
  get 'parking', to: 'home#parking'
  get 'help', to:'home#help'
  post 'help', to: 'home#create_helper'
  get 'price', to:'home#price'
  get 'home/floors', to:'home#get_floors'

  namespace :client do
    resources :booking do
      collection do
        get 'get_floors'
        get 'get_slot_detail'
        put 'cancel_slot'
      end
    end
    resources :profile do
      member do
        get 'create_profile'
        delete 'destroy_vehicle'
        get 'history'
      end
      collection do
        patch 'update_password'
        patch 'upload_avatar'
        post 'create_vehicle'
      end
    end
  end

  namespace :admin do
    resources :booking
    resources :managers do
      collection do
        get 'edit_profile'
        patch 'update_profile'
        get 'edit_password'
        patch 'update_password'
        get 'update_parking'
        get 'remove_parking'
        get 'get_manager'
        get 'clients'
        get 'get_profile'
        get 'helps'
        get 'help_isread'
        put 'manager_reset_password'
      end
    end
    resources :parking do
      collection do
        get 'get_floors'
      end
    end
  end

  namespace :manager do
    resources :booking, only: [:index] do
      collection do
        get 'load_park'
        get 'get_slot_detail'
        post 'slot_book'
        put 'pay'
        get 'get_reserve_detail'
        put 'cancel_reserve'
        post 'accept_reserve'
        get 'find_bks'
      end
    end
    resources :profile, only: [:edit, :update] do
      member do
        get 'payment_history'
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

  <a class="navbar-brand mr-1" href="<%= admin_booking_index_path %>">Dana Parking</a>
  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars fa-lg"></i>
  </button>

  <div class="d-none d-md-inline-block ml-auto mr-0 mr-md-3 my-2 my-md-0"></div>

  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle fa-lg"></i> &nbsp; <i class="fas fa-caret-down"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="<%= edit_profile_admin_managers_path %>">Thiết lập tài khoản</a>
        <a class="dropdown-item" href="<%= edit_password_admin_managers_path %>">Thay đổi mật khẩu</a>
        <div class="dropdown-divider"></div>
        <%= link_to 'Đăng xuất', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </li>
  </ul>

</nav>

app/views/layouts/admin/_menu.html.erb
<ol class="breadcrumb">
  Hi <b style="margin: 0px 5px;"><%= @admin.profile.first_name || '' %></b> !
</ol>

<!-- <div class="row">
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-primary o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-comments"></i>
        </div>
        <div class="mr-5">26 New Messages!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-warning o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-list"></i>
        </div>
        <div class="mr-5">11 New Tasks!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-success o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-shopping-cart"></i>
        </div>
        <div class="mr-5">123 New Orders!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
  <div class="col-xl-3 col-sm-6 mb-3">
    <div class="card text-white bg-danger o-hidden h-100">
      <div class="card-body">
        <div class="card-body-icon">
          <i class="fas fa-fw fa-life-ring"></i>
        </div>
        <div class="mr-5">13 New Tickets!</div>
      </div>
      <a class="card-footer text-white clearfix small z-1" href="#">
        <span class="float-left">View Details</span>
        <span class="float-right">
          <i class="fas fa-angle-right"></i>
        </span>
      </a>
    </div>
  </div>
</div> -->

app/views/layouts/admin/_sidebar.html.erb
<style media="screen">
  .helps-number {
    width: 20px;
    position: absolute;
    height: 20px;
    text-align: center;
    border-radius: 50%;
    right: 40%;
    top: 15%;
    font-size: 14px;
    background: linear-gradient(40deg,#2096ff,#05ffa3)!important;
  }
</style>

<ul class="sidebar navbar-nav">
  <li class="nav-item <%= active_class? admin_booking_index_path %>">
    <a class="nav-link" href="<%= admin_booking_index_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Tổng Quan</span>
    </a>
  </li>
  <li class="nav-item <%= 'active' if ['managers', 'parking'].include?(controller_name) && !['edit_password', 'edit_profile', 'clients', 'helps'].include?(action_name) %> dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="pagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-fw fa-folder"></i>
      <span>Quản Lý</span>
    </a>
    <div class="dropdown-menu" aria-labelledby="pagesDropdown">
      <h6 class="dropdown-header">Quản lý nhân viên :</h6>
      <a class="dropdown-item" href="<%= new_admin_manager_path %>">Tạo mới nhân viên</a>
      <a class="dropdown-item" href="<%= admin_managers_path %>">Danh sách nhân viên</a>
      <div class="dropdown-divider"></div>
      <h6 class="dropdown-header">Quản lý bãi đỗ :</h6>
      <a class="dropdown-item" href="<%= new_admin_parking_path %>">Thêm mới bãi đỗ</a>
      <a class="dropdown-item" href="<%= admin_parking_index_path %>">Các bãi đỗ</a>
    </div>
  </li>
  <li class="nav-item <%= 'active' if action_name == 'clients' %>">
    <a class="nav-link" href="<%= clients_admin_managers_path %>">
      <i class="fas fa-fw fa-table"></i>
      <span>Khách Hàng</span>
    </a>
  </li>
  <li class="nav-item <%= 'active' if action_name == 'helps' %>" style="position: relative;">
    <% if @unreads > 0 %>
    <div class="helps-number"><span><%= @unreads %></span></div>
    <% end %>
    <a class="nav-link" href="<%= helps_admin_managers_path %>">
      <i class="fas fa-fw fa-table"></i>
      <span>Phản Hồi</span>
    </a>
  </li>
</ul>