config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :home, only: :index
  root 'home#index'
  get 'parking', to: 'home#parking'
  get 'help', to:'home#help'
  post 'help', to: 'home#create_helper'
  get 'price', to:'home#price'
  get 'home/floors', to:'home#get_floors'

  namespace :client do
    resources :booking do
      collection do
        get 'get_floors'
        get 'get_slot_detail'
        put 'cancel_slot'
      end
    end
    resources :profile do
      member do
        get 'create_profile'
        delete 'destroy_vehicle'
        get 'history'
      end
      collection do
        patch 'update_password'
        patch 'upload_avatar'
        post 'create_vehicle'
      end
    end
  end

  namespace :admin do
    resources :booking
    resources :managers do
      collection do
        get 'edit_profile'
        patch 'update_profile'
        get 'edit_password'
        patch 'update_password'
        get 'update_parking'
        get 'remove_parking'
        get 'get_manager'
        get 'clients'
        get 'get_profile'
        get 'helps'
        get 'help_isread'
        put 'manager_reset_password'
      end
    end
    resources :parking do
      collection do
        get 'get_floors'
      end
    end
  end

  namespace :manager do
    resources :booking, only: [:index] do
      collection do
        get 'load_park'
        get 'get_slot_detail'
        post 'slot_book'
        put 'pay'
        get 'get_reserve_detail'
        put 'cancel_reserve'
        post 'accept_reserve'
        get 'find_bks'
      end
    end
    resources :profile, only: [:edit, :update] do
      member do
        get 'payment_history'
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def parking
    @parkings = Parking.where(active: true).pluck(:id, :address)
  end

  def help
    @helper = Helper.new
  end

  def create_helper
    @helper = Helper.new help_params
    if @helper.save
      flash[:success] = 'Thành công.'
    else
      flash[:error] = 'Thất bại!'
    end
    redirect_to help_path
  end

  def price
    @size_1 = Floor.includes(:parking).where(size: '1')
    @size_2 = Floor.includes(:parking).where(size: '2')
    @size_3 = Floor.includes(:parking).where(size: '3')
  end

  def get_floors
    @floors = Floor.get_floors(params[:park_id], params[:block_size])
    respond_to do |format|
      if params[:park_id].nil? || params[:block_size].nil? || @floors.nil?
        format.json { render json: false, status: 404 }
      else
        format.json { render json: @floors.as_json(except: [:created_at, :updated_at], include: { blocks: { only: [:id, :name], include: { parking_slots: { except: [:created_at, :updated_at, :block_id] }} }}), status: :ok }
      end
    end
  end

  private
  def help_params
    params.require(:helper).permit(:name, :email, :phone, :content)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/help.html.erb
<style media="screen">
  .content-center {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .flex-end {
    text-align: center;
  }
  input.error {
    margin: 0;
    margin-top: 20px;
  }
  label.error {
    color: red;
    font-weight: 500;
    padding-left: 5px;
    font-size: 14px;
    margin-bottom: 20px;
  }
</style>

<div class="wrapper">
  <div class="container">
    <%= render 'layouts/home/header' %>

    <div class="row content-center" style="width: 100%">
      <h3>Bạn có gì muốn nhắn nhủ gì?</h3>
    </div>
    <div class="form-gop-y">
      <div class="row content-center">
        <span><i class="fa fa-envelope" aria-hidden="true"></i>danaparking.com.vn</span>
        <span><i class="fa fa-phone" aria-hidden="true"></i>1900000</span>
      </div>
      <%= form_for @helper, url: help_path do |f| %>
        <div class="form-row">
          <div class="col-4">
            <%= f.text_field :name, class: 'form-control', placeholder: 'Họ và tên' %>
          </div>
          <div class="col-4">
            <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
          </div>
          <div class="col-4">
            <%= f.phone_field :phone, class: 'form-control phone', placeholder: 'Số điện thoại' %>
          </div>
          <div class="col-12">
            <%= text_area(:helper, :content, rows: 5, class: 'form-control', placeholder: 'Nội dung') %>
          </div>
          <div class="col-12 flex-end">
            <%= f.submit 'Gửi', class: 'btn btn-outline-success' %>
          </div>
        </div>
      <% end %>
    </div>

</div>
</div>

app/views/home/index.html.erb
<div class="wrapper">
  <div class="container">
    <!-- HEADER -->
    <div class="header-container">

      <div class="top-header">
        <div class="right-nav float-right">
          <ul>
            <li><a href="<%= new_user_session_path %>">Đăng nhập</a></li>
            <li><a href="<%= new_user_registration_path %>">Đăng ký</a></li>
          </ul>
        </div>
      </div>

      <div class="bot-header">
        <a class="brand-logo" href="<%= root_path %>"><img src="https://github.com/hmtoan96/theme-parking/raw/master/logo.png"></a>
        <div class="navigation float-right">
          <ul>
            <li><a href="<%= root_path %>">Trang Chủ</a></li>
            <li><a href="<%= parking_path%>">Bãi xe</a></li>
            <li><a href="<%= price_path %>">Bảng giá</a></li>
            <li><a href="<%= help_path %>">Phản hồi</a></li>
          </ul>
        </div>
      </div>
      <div class="row h-100" style="width: 100%">
        <div class="mt-4 col-12 col-lg-6 d-flex flex-column justify-content-center align-items-start">
          <header class="entry-header">
             <h1>DANA <br>Car Parking</h1>
          </header>

          <div class="entry-content mt-4">
            <p>Do nhu cầu kiểm soát an ninh trật tự tại các bãi đỗ xe của các nhà máy, khu chung cư, trung tâm thương mại,
                  siêu thị lớn với lượng xe ra vào lớn dẫn tới khâu quản lý tại các bãi đậu xe trở nên khó khăn,
                  phức tạp quá tải.
                  Để đảm bảo an ninh trật tự, bảo vệ tài sản của mỗi cá nhân hệ thống quản lý bãi đỗ xe
                  thông minh ra đời đã đáp ứng được nhu cầu cần thiết,
                   cấp bách giảm thiểu rủi ro và sức lực cho con người.</p>
          </div>

          <footer class="entry-footer d-flex flex-wrap align-items-center mt-4">

          </footer>
        </div>
        <div class="col-12 col-lg-6 d-flex flex-column justify-content-center align-items-start">

          <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="<%= asset_path 'driver.jpg' %>" style="max-width: 100%" alt="">
              </div>
              <div class="carousel-item">
                <img src="<%= asset_path 'slide-1.jpeg' %>" style="max-width: 100%" alt="">
              </div>
              <div class="carousel-item">
                <img src="<%= asset_path 'slide-2.jpeg' %>" style="max-width: 100%; max-height: 277px" alt="">
              </div>
            </div>
          </div>
        </div>

        <div class="maps col-12 col-lg-12 d-flex flex-column justify-content-center align-items-start">

            <h1 style="margin-left: 236px" class="text-center">Chúng tôi dẫn đường cho bạn</h1>

          <iframe height="400" src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=Da%20Nang+(My%20Business%20Name)&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"><a href="https://www.maps.ie/map-my-route/">Create route map</a></iframe></div><br />
        </div>
        <div class="our-service">
          <h1 class="text-center">Chúng tôi đã làm gì?</h1>
        </div>
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
<ol class="carousel-indicators">
  <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
  <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
  <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
</ol>
<div class="carousel-inner">
                        <div class="carousel-item active">
                                <img src="<%=asset_path '01_hero_banner.jpg' %>" style="max-width: 100%" alt="">
                                <div class="service-item">
                                  <h4>Giá cả phải chăng</h4>
                                  <p>Mức giá rẻ phù hợp cho mọi người. Bạn chỉ việc trả tiền đúng trên trang web
                    và an tâm tận hưởng bãi xe.</p>
                                  <a href="<%= price_path %>" class="button gradient-bg">Xem thêm</a>
                                </div>
                              </div>
                              <div class="carousel-item">
                                <img src="<%=asset_path '02_hero_banner.jpg' %>" style="max-width: 100%" alt="">
                                <div class="service-item">
                                  <h4>Cải thiện dịch vụ.</h4>
                                  <p>Dịch vụ luôn luôn được cải thiện tốt nhất để phục vụ khách hàng.</p>
                                  <!-- <a href="javascript:void(0)" class="button gradient-bg">Read more</a> -->
                                </div>
                              </div>
                              <div class="carousel-item">
                                <img src="<%=asset_path '03_hero_banner.png' %>" style="max-width: 100%;" alt="">
                                <div class="service-item">
                                  <h4>Lựa chọn tốt hơn</h4>
                                  <p>Là một lựa chọn chủ động cho bạn. Khi đã nắm bắt lấy thông tin về bãi đậu và đặt trước một chỗ cho xe của mình để không phải loay hoay tìm chỗ để bên đường.</p>
                                  <!-- <a href="javascript:void(0)" class="button gradient-bg">Read more</a> -->
                                </div>
                              </div>
                            </div>
                </div>
<h1 class="text-center" style="margin: 30px 0">Chúng tôi sẵn sàng trợ giúp</h1>
<div class="subscribe-banner">
    <div class="container">
      <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">

          <p style="color: white">Nhận hỗ trợ chỉ với vài thao tác chạm. Bạn cũng có thể tìm câu trả lời cho những thắc mắc của mình ở phần Trợ giúp.</p>
          <h4 style="margin-top: 10px; text-decoration: underline;"><a style="color: white" href="<%= help_path %>">Click vào đây >>></a></h4>
</div>
</div>
</div>
</div>
<footer class="site-footer">
<div class="footer-widgets">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 col-lg-4">
        <div class="foot-about">
          <h2><a href="javascript:void(0)">DANA PARK</a></h2>

            <p>Là nơi để bạn trao trọn niềm tin.</p>

            <p class="copyright">Copyright &copy;<script>document.write(new Date().getFullYear());</script> DANACARPARKING</p>
            </div><!-- .foot-about -->
          </div><!-- .col -->

      <div class="col-12 col-md-6 col-lg-4 mt-5 mt-md-0">
        <div class="foot-contact">
          <h2>Liên hệ</h2>
          <ul class="p-0 m-0">
            <li><span>Địa chỉ :</span></li>
            <li><span>Điện thoại:</span></li>
            <li><span>Email :</span></li>
          </ul>
        </div>
      </div><!-- .col -->

    </div><!-- .row -->
  </div><!-- .container -->
</div><!-- .footer-widgets -->
</footer><!-- .site-footer -->
</div>
</div>
</div>

app/views/home/parking.html.erb
<style media="screen">
  .nav-tabs .nav-item.show .nav-link, .nav-tabs .nav-link.active {
    color: #007bff;
  }
</style>
<div class="container">
<%= render 'layouts/home/header' %>
  <div class="select-parking">
    <div class="form-group">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-6">
          <label for="selectPark">Bãi: </label>
          <select id="selectPark" class="form-control">
            <option value="0">Chọn bãi</option>
            <% @parkings.each do |p| %>
            <option value="<%= p[0] %>"><%= p[1] %></option>
            <% end %>
          </select>
        </div>
        <div class="col-md-4">
          <label for="selectSlot">Số chỗ: </label>
          <select id="selectSlot" class="form-control">
            <option value="0">Loại xe của bạn</option>
            <option value="1">4 - 7</option>
            <option value="2">12 - 16</option>
            <option value="3"> Trên 16 chỗ</option>
          </select>
        </div>
      </div>
    </div>
  </div>

  <div class="result-parking container">
    <div class="row">
      <div class="col-1"></div>
      <div class="col-9">
        <ul class="nav nav-tabs" id="resultTab" role="tablist">
          <li class="nav-item" style="display: none;">
            <a class="nav-link" data-toggle="tab" role="tab" href="#" aria-controls="" aria-selected="false"></a>
          </li>
        </ul>
        <div class="tab-content" id="resultTabContent">
          <div class="tab-pane show" id="" role="tabpanel" aria-labelledby="" style="display: none;">
            <div class="container">
              <ul class="row slot-list-items">
              </ul>
            </div>
          </div>
        </div>
        <%= render 'layouts/note' %>
      </div>

    </div>
  </div>

</div>

app/views/home/price.html.erb
<div class="wrapper">
  <div class="container">
    <!-- HEADER -->
    <%= render 'layouts/home/header' %>
    <div class="price-container">
      <h1 class="text-center" style="margin: 50px 0">Bảng giá</h1>
      <div class="places">
        <ul class="text-center">
          <li>
            <a href="javascript:void(0)"><i class="fa fa-car fa-2x selected" data-size="0"></i></a>
            <p>4-7 chỗ</p>
          </li>
          <li>
            <a href="javascript:void(0)"><i class="fa fa-car fa-2x" data-size="1"></i></a>
            <p>12-16 chỗ</p>
          </li>
          <li>
            <a href="javascript:void(0)"><i class="fa fa-car fa-2x" data-size="2"></i></a>
            <p>Trên 16 chỗ</p>
          </li>
        </ul>
      </div>
      <table class="price-table">
        <thead>
          <th colspan="3" class="text-center">
            Giá cước 4-7 chỗ
          </th>
        </thead>
        <tbody>
          <% @size_1.each do |s| %>
          <tr>
            <td><%= s.parking.address %></td>
            <td><%= number_with_delimiter(s.price_by_hours.to_i, delimiter: ".") %>đ/Giờ</td>
            <td><%= number_with_delimiter(s.price_by_months.to_i, delimiter: ".") %>đ/Tháng</td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <table class="price-table price-table-hidden">
        <thead>
          <th colspan="3" class="text-center">
            Giá cước 12-16 chỗ
          </th>
        </thead>
        <tbody>
          <% @size_2.each do |s| %>
          <tr>
            <td><%= s.parking.address %></td>
            <td><%= number_with_delimiter(s.price_by_hours.to_i, delimiter: ".") %>đ/Giờ</td>
            <td><%= number_with_delimiter(s.price_by_months.to_i, delimiter: ".") %>đ/Tháng</td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <table class="price-table price-table-hidden">
        <thead>
          <th colspan="3" class="text-center">
            Giá cước trên 16 chỗ
          </th>
        </thead>
        <tbody>
          <% @size_3.each do |s| %>
          <tr>
            <td><%= s.parking.address %></td>
            <td><%= number_with_delimiter(s.price_by_hours.to_i, delimiter: ".") %>đ/Giờ</td>
            <td><%= number_with_delimiter(s.price_by_months.to_i, delimiter: ".") %>đ/Tháng</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>