config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :home, only: :index
  root 'home#index'
  get 'parking', to: 'home#parking'
  get 'help', to:'home#help'
  post 'help', to: 'home#create_helper'
  get 'price', to:'home#price'
  get 'home/floors', to:'home#get_floors'

  namespace :client do
    resources :booking do
      collection do
        get 'get_floors'
        get 'get_slot_detail'
        put 'cancel_slot'
      end
    end
    resources :profile do
      member do
        get 'create_profile'
        delete 'destroy_vehicle'
        get 'history'
      end
      collection do
        patch 'update_password'
        patch 'upload_avatar'
        post 'create_vehicle'
      end
    end
  end

  namespace :admin do
    resources :booking
    resources :managers do
      collection do
        get 'edit_profile'
        patch 'update_profile'
        get 'edit_password'
        patch 'update_password'
        get 'update_parking'
        get 'remove_parking'
        get 'get_manager'
        get 'clients'
        get 'get_profile'
        get 'helps'
        get 'help_isread'
        put 'manager_reset_password'
      end
    end
    resources :parking do
      collection do
        get 'get_floors'
      end
    end
  end

  namespace :manager do
    resources :booking, only: [:index] do
      collection do
        get 'load_park'
        get 'get_slot_detail'
        post 'slot_book'
        put 'pay'
        get 'get_reserve_detail'
        put 'cancel_reserve'
        post 'accept_reserve'
        get 'find_bks'
      end
    end
    resources :profile, only: [:edit, :update] do
      member do
        get 'payment_history'
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/parking.rb
class Parking < ApplicationRecord
  has_many :floors, dependent: :destroy

  accepts_nested_attributes_for :floors, allow_destroy: true, reject_if: :all_blank
end

app/controllers/admin/parking_controller.rb
class Admin::ParkingController < Admin::BaseController
  before_action :set_parking, only: [:edit, :update, :destroy]

  def index
    @parkings = Parking.all.pluck(:id, :address, :active)
  end

  def new
    @parking = Parking.new
    @floor = @parking.floors.build(name: '1')
    @block = @floor.blocks.build
  end

  def edit
    @parking.floors
  end

  def create
    @parking = Parking.new parking_params
    if @parking.save
      flash[:success] = 'Đã lưu.'
    else
      flash[:error] = 'Thất bại !'
    end
    redirect_to new_admin_parking_path
  end

  def update
    if @parking.update parking_params
      flash[:success] = 'Đã lưu.'
    else
      flash[:error] = 'Thất bại !'
    end
    redirect_to admin_parking_index_path
  end

  def get_floors
    @floors = Floor.get_floors(params[:park_id], params[:block_size])
    respond_to do |format|
      if params[:park_id].nil? || params[:block_size].nil? || @floors.nil?
        format.json { render json: false, status: 404 }
      else
        format.json { render json: @floors.as_json(except: [:created_at, :updated_at], include: { blocks: { only: [:id, :name], include: { parking_slots: { except: [:created_at, :updated_at, :block_id] }} }}), status: :ok }
      end
    end
  end

  def destroy
    if (@parking.active == true && @parking.update(active: false)) || (@parking.active == false && @parking.update(active: true))
      flash[:success] = 'Đã lưu.'
    else
      flash[:error] = 'Thất bại !'
    end
    redirect_to admin_parking_index_path
  end

  private

  def parking_params
    params.require(:parking).permit(:id, :address, floors_attributes: [:id, :name, :size, :price_by_hours, :price_by_months, :_destroy, blocks_attributes: [:id, :name, :_destroy, :slots]])
  end
  def set_parking
    @parking = Parking.find_by id: params[:id]
  end
end

app/helpers/admin/parking_helper.rb
module Admin::ParkingHelper
end

app/views/admin/parking/edit.html.erb
<style media="screen">
  fieldset.scheduler-border {
    border: 1px solid #33C4FF ;
    padding: 0 1.4em 1.4em 1.4em !important;
    margin: 0 0 1.5em 0 !important;
    border-radius: 10px;
  }

  legend.scheduler-border {
    font-size: 1.2em !important;
    font-weight: bold !important;
    text-align: left !important;
    width:auto;
    padding:0 10px;
  }
</style>
<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
          Thêm bãi đỗ
        </div>
        <div class="card-body">
          <h4 class="text-center">Sửa bãi đỗ</h4>

          <%= form_for @parking, url: admin_parking_path, method: :put, html: { class: 'main-form' } do |f| %>

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= f.label :address do %>
                    <b>Tên bãi đỗ</b>
                  <% end %>
                  <%= f.text_field :address, class: 'form-control' %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-10"></div>
              <div class="col-md-2">
                <button id="btn-floor" class="btn btn-primary">
                  <i class="fas fa-plus-circle"></i> Thêm Bãi
                </button>
              </div>
            </div>

            <%= f.fields_for :floors do |ff| %>
            <div class="form-group form-floors">
              <%= ff.hidden_field :name %>
              <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                  <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Bãi <%= ff.object.name %></legend>
                    <%= ff.hidden_field '_destroy' %>
                    <div class="row">
                      <div class="col-md-3">
                        <%= ff.label :size, 'Số chỗ ngồi' %>
                        <%= ff.select :size, options_for_select([['4 - 7', '1'], ['12 - 16', '2'], ['> 16', '3']], selected: ff.object.size), { include_blank: "Chọn số chỗ ngồi"}, class: 'form-control' %>
                      </div>
                      <div class="col-md-3">
                        <%= ff.label :price_by_hours, 'Giá tiền theo giờ' %>
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text">VND</span>
                          </div>
                          <%= ff.number_field :price_by_hours, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-3">
                        <%= ff.label :price_by_months, 'Giá tiền theo tháng' %>
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text">VND</span>
                          </div>
                          <%= ff.number_field :price_by_months, class: 'form-control' %>
                        </div>
                      </div>
                      <div class="col-md-2">
                        <button class="btn btn-primary btn-block">
                          <i class="fas fa-plus-circle"></i> Khu
                        </button>
                      </div>
                      <div class="col-md-1">
                        <button class="btn btn-info btn-reset" style="margin-top: 0px;">
                          <i class="fas fa-redo"></i>
                        </button>
                      </div>
                    </div>

                    <hr>

                    <%= ff.fields_for :blocks do |fff| %>
                    <div class="form-blocks">
                      <div class="row">
                        <div class="col-sm-3">
                          <b>Khu: </b>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-9">
                          <div class="form-group form-sub-blocks">
                            <div class="row">
                              <div class="col-md-5">
                                <%= fff.text_field :name, class: 'form-control', placeholder: 'Tên khu' %>
                              </div>
                              <span></span>
                              <div class="col-md-5">
                                <%= fff.text_field :slots, class: 'form-control', placeholder: 'Số lượng chỗ', value: fff.object.parking_slots.size %>
                              </div>
                              <div class="col-md-2"></div>
                              <%= fff.hidden_field '_destroy' %>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <% end %>

                  </fieldset>
                </div>
                <div class="col-md-1"></div>
              </div>
            </div>
            <% end %>

            <div class="col-4">
              <%= f.submit 'Lưu', class: 'btn btn-primary btn-md', type: 'submit' %>
              <%= link_to 'Quay lại', :back, class: 'btn btn-outline-info btn-md waves-effect' %>
            </div>

          <% end %>
        </div>
      </div>
    </div>

    <footer class="sticky-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © DANA CAR PARKING 2019</span>
        </div>
      </div>
    </footer>

  </div>

</div>

app/views/admin/parking/index.html.erb
<style media="screen">
  .btn-teal {
    background-color: #00796b!important;
    border-radius: 10em;
    margin-right: 10px;
  }
  table.table a, .btn {
    color: #fff;
  }
  .btn-danger, .btn-primary {
    border-radius: 10em;
  }
  .btn:hover {
    color: #fff;
  }
  .thead {
    font-size: 1rem;
    font-weight: 600;
  }
  .active {
    color: #30c730;
  }
  .slot-item a {
    pointer-events: none;
  }
</style>

<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
          Thông tin các bãi
        </div>
        <div class="card-body">

          <div class="select-parking">
            <div class="form-group">
              <div class="row">
                <div class="col-md-5">
                  <label for="selectPark">Bãi: </label>
                  <select id="selectPark" class="form-control">
                    <option value="0">Chọn bãi</option>
                    <% @parkings.each do |p| %>
                      <% if p[2] %>
                      <option value="<%= p[0] %>"><%= p[1] %></option>
                      <% end %>
                    <% end %>
                  </select>
                </div>
                <div class="col-md-3">
                  <label for="selectSlot">Số chỗ: </label>
                  <select id="selectSlot" class="form-control">
                    <option value="0">Chọn số chỗ ngồi</option>
                    <option value="1">4 - 7</option>
                    <option value="2">12 - 16</option>
                    <option value="3">> 16</option>
                  </select>
                </div>
              </div>
              <div class="form-group" style="margin: 10px 0px;">
                <div class="row">
                  <div class="col-md-2">
                    <label>Người Quản Lý Bãi: </label>
                  </div>
                  <div class="col-md-3">
                    <b id="manager-name"></b>
                  </div>
                </div>
              </div>
            </div>


            <div class="result-parking container">
              <div class="form-group">
                <div class="row">
                  <div class="col-11 mx-auto">
                    <ul class="nav nav-tabs" id="resultTab" role="tablist">
                      <li class="nav-item" style="display: none;">
                        <a class="nav-link" data-toggle="tab" role="tab" href="#" aria-controls="" aria-selected="false">401</a>
                      </li>
                    </ul>

                    <div class="tab-wrapper">
                      <div class="tab-content" id="resultTabContent">
                        <div class="tab-pane show" id="" role="tabpanel" aria-labelledby="" style="display: none;">
                          <div class="container">
                            <ul class="row slot-list-items">
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>
                  <div class="col-11 mx-auto" style="padding-left: 0;">
                    <%= render 'layouts/note' %>
                  </div>
                </div>

              </div>
            </div>
          </div>

        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
          Danh sách các bãi
        </div>
        <div class="card-body">
          <table class="table table-striped table-responsive-md btn-table">
            <thead class="thead">
              <tr>
                <th>#</th>
                <th>Bãi Đỗ</th>
                <th>Trạng Thái</th>
                <th>Tác Vụ</th>
              </tr>
            </thead>

            <tbody>
              <% if @parkings.size == 0 %>
              <tr>
                <td colspan="4" class="text-center">
                  <strong>Chưa có dữ liệu</strong>
                </td>
              </tr>
              <% end %>
              <% @parkings.each_with_index do |p,i| %>
              <tr>
                <th scope="row" style="vertical-align: middle;"><%= i+1 %></th>
                <td><%= p[1] %></td>
                <td><%= p[2] ? '<i class="fas fa-dot-circle active"></i> Hoạt động'.html_safe : '<i class="fas fa-dot-circle"></i> Đóng cửa'.html_safe %></td>
                <td>
                  <%= link_to 'Sửa bãi', edit_admin_parking_path(p[0]), class: 'btn btn-teal btn-rounded btn-sm m-0' %>
                  &nbsp;
                  <% if p[2] %>
                  <%= link_to 'Đóng bãi', admin_parking_path(p[0]), class: 'btn btn-danger btn-rounded btn-sm m-0', method: :delete, data: { confirm: 'Bạn có chắc chắn muốn đóng bãi này ?' } %>
                  <% else %>
                  <%= link_to 'Mở bãi', admin_parking_path(p[0]), class: 'btn btn-primary btn-rounded btn-sm m-0', method: :delete, data: { confirm: 'Bạn có chắc chắn muốn mở bãi này ?' } %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/parking/new.html.erb
<style media="screen">
  fieldset.scheduler-border {
    border: 1px solid #33C4FF ;
    padding: 0 1.4em 1.4em 1.4em !important;
    margin: 0 0 1.5em 0 !important;
    border-radius: 10px;
  }
  legend.scheduler-border {
    font-size: 1.2em !important;
    font-weight: bold !important;
    text-align: left !important;
    width:auto;
    padding:0 10px;
  }
  input.error {
    margin: 0;
  }
  label.error {
    color: red;
    font-weight: 500;
    padding-left: 5px;
    font-size: 14px;
    margin-bottom: 0;
  }
</style>
<div id="wrapper">

  <%= render 'layouts/admin/sidebar' %>

  <div id="content-wrapper">

    <div class="container-fluid">

      <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
          Thêm bãi đỗ
        </div>
        <div class="card-body">
          <h4 class="text-center">Tạo mới bãi đỗ</h4>

          <%= form_for @parking, url: admin_parking_index_path, html: { class: 'main-form' } do |f| %>

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <%= f.label :address do %>
                    <b>Tên bãi đỗ</b>
                  <% end %>
                  <%= f.text_field :address, class: 'form-control required' %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-10"></div>
              <div class="col-md-2">
                <button id="btn-floor" class="btn btn-primary">
                  <i class="fas fa-plus-circle"></i> Thêm Bãi
                </button>
              </div>
            </div>

            <%= f.fields_for :floors do |ff| %>
            <div class="form-group form-floors">
              <%= ff.hidden_field :name %>
              <div class="row">
                <div class="col-md-1"></div>
                <div class="col-md-10">
                  <fieldset class="scheduler-border">
                    <legend class="scheduler-border">Bãi 1</legend>
                    <div class="row">
                      <div class="col-md-3">
                        <%= ff.label :size, 'Số chỗ ngồi' %>
                        <%= ff.select :size, options_for_select([['4 - 7', '1'], ['12 - 16', '2'], ['> 16', '3']]), { include_blank: "Chọn số chỗ ngồi"}, class: 'form-control required' %>
                      </div>
                      <div class="col-md-3">
                        <%= ff.label :price_by_hours, 'Giá tiền theo giờ' %>
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text">VND</span>
                          </div>
                          <%= ff.number_field :price_by_hours, class: 'form-control required' %>
                        </div>
                      </div>
                      <div class="col-md-3">
                        <%= ff.label :price_by_months, 'Giá tiền theo tháng' %>
                        <div class="input-group">
                          <div class="input-group-prepend">
                            <span class="input-group-text">VND</span>
                          </div>
                          <%= ff.number_field :price_by_months, class: 'form-control required' %>
                        </div>
                      </div>
                      <div class="col-md-2">
                        <button class="btn btn-primary btn-block">
                          <i class="fas fa-plus-circle"></i> Khu
                        </button>
                      </div>
                      <div class="col-md-1">
                        <button class="btn btn-info btn-reset" style="margin-top: 0px;">
                          <i class="fas fa-redo"></i>
                        </button>
                      </div>
                    </div>

                    <hr>

                    <%= ff.fields_for :blocks do |fff| %>
                    <div class="form-blocks">
                      <div class="row">
                        <div class="col-sm-3">
                          <b>Khu: </b>
                        </div>
                      </div>
                      <div class="row">
                        <div class="col-md-1"></div>
                        <div class="col-md-9">
                          <div class="form-group form-sub-blocks">
                            <div class="row">
                              <div class="col-md-5">
                                <%= fff.text_field :name, class: 'form-control required', placeholder: 'Tên khu' %>
                              </div>
                              <span></span>
                              <div class="col-md-5">
                                <%= fff.text_field :slots, class: 'form-control required', placeholder: 'Số lượng chỗ' %>
                              </div>
                              <div class="col-md-2"></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <% end %>

                  </fieldset>
                </div>
                <div class="col-md-1"></div>
              </div>
            </div>
            <% end %>

            <div class="col-3">
              <%= f.submit 'Lưu', class: 'btn btn-primary' %>
            </div>

          <% end %>
        </div>
      </div>
    </div>

    <footer class="sticky-footer">
      <div class="container my-auto">
        <div class="copyright text-center my-auto">
          <span>Copyright © DANA CAR PARKING 2019</span>
        </div>
      </div>
    </footer>

  </div>

</div>